[bot-cherry-pick]Test pr 10

diff --git a/bin/pulsar-daemon b/bin/pulsar-daemon
--- a/bin/pulsar-daemon
+++ b/bin/pulsar-daemon
@@ -38,7 +38,17 @@ EOF
 }
 
 BINDIR=$(dirname "$0")
+<<<<<<< HEAD
 PULSAR_HOME=$(cd $BINDIR/..;pwd)
+=======
+PULSAR_HOME=$(cd -P $BINDIR/..;pwd)
+
+# Check bookkeeper env and load bkenv.sh
+if [ -f "$PULSAR_HOME/conf/bkenv.sh" ]
+then
+    . "$PULSAR_HOME/conf/bkenv.sh"
+fi
+>>>>>>> f773c602c... Test pr 10 (#27)
 
 if [ -f "$PULSAR_HOME/conf/pulsar_env.sh" ]
 then
@@ -50,11 +60,26 @@ PULSAR_LOG_APPENDER=${PULSAR_LOG_APPENDER:-"RollingFile"}
 PULSAR_STOP_TIMEOUT=${PULSAR_STOP_TIMEOUT:-30}
 PULSAR_PID_DIR=${PULSAR_PID_DIR:-$PULSAR_HOME/bin}
 
+<<<<<<< HEAD
 if [ $# -lt 2 ]
 then
     echo "Error: no enough arguments provided."
     usage
     exit 1
+=======
+if [ $# = 0 ]; then
+    usage
+    exit 1
+elif [ $# = 1 ]; then
+    if [ $1 == "--help" -o $1 == "-h" ]; then
+        usage
+        exit 1
+    else
+        echo "Error: no enough arguments provided."
+        usage
+        exit 1
+    fi
+>>>>>>> f773c602c... Test pr 10 (#27)
 fi
 
 startStop=$1
@@ -138,6 +163,10 @@ case $startStop in
 
     rotate_out_log $out
     echo starting $command, logging to $logfile
+<<<<<<< HEAD
+=======
+    echo Note: Set immediateFlush to true in conf/log4j2.yaml will guarantee the logging event is flushing to disk immediately. The default behavior is switched off due to performance considerations.
+>>>>>>> f773c602c... Test pr 10 (#27)
     pulsar=$PULSAR_HOME/bin/pulsar
     nohup $pulsar $command "$@" > "$out" 2>&1 < /dev/null &
     echo $! > $pid
